spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qa
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update